### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by lsih** [sadhen/shiji#3]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 8: illegal multibyte sequence

**Comment by da-liii** [comment]
How to reproduce it?

**Comment by lsih** [comment]
python3 generate.py -t kindle
I will generate shiji.epub for Kindle
Converting the source file to Markdown format...
Traceback (most recent call last):
  File "D:\Download\shiji-master\generate.py", line 175, in <module>
    convert(i, save)
  File "D:\Download\shiji-master\generate.py", line 29, in convert
    content = getLine(data)
  File "D:\Download\shiji-master\generate.py", line 11, in getLine
    for line in data:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 8: illegal multibyte sequence

**Comment by cuixiping** [comment]
You should add encoding parameter to all `open(...) ` calls. For example

```
fout = open(filename, "w", encoding="utf-8")
```
